// Retro — generated by @web-kits/audio (do not edit)
// patch: Retro
import type { SoundDefinition, SoundPatch } from "@web-kits/audio";

export const tap: SoundDefinition = {"source":{"type":"square","frequency":880},"envelope":{"attack":0,"decay":0.02,"sustain":0,"release":0.006},"gain":0.15};
export const click: SoundDefinition = {"source":{"type":"square","frequency":660},"envelope":{"attack":0,"decay":0.025,"sustain":0,"release":0.008},"gain":0.18};
export const keyPress: SoundDefinition = {"source":{"type":"square","frequency":1047},"envelope":{"attack":0,"decay":0.015,"sustain":0,"release":0.005},"gain":0.12};
export const toggleOn: SoundDefinition = {"layers":[{"source":{"type":"square","frequency":523},"envelope":{"attack":0,"decay":0.03,"sustain":0,"release":0.01},"gain":0.16},{"source":{"type":"square","frequency":784},"envelope":{"attack":0,"decay":0.03,"sustain":0,"release":0.01},"delay":0.04,"gain":0.14}]};
export const toggleOff: SoundDefinition = {"layers":[{"source":{"type":"square","frequency":784},"envelope":{"attack":0,"decay":0.03,"sustain":0,"release":0.01},"gain":0.16},{"source":{"type":"square","frequency":523},"envelope":{"attack":0,"decay":0.03,"sustain":0,"release":0.01},"delay":0.04,"gain":0.14}]};
export const checkbox: SoundDefinition = {"source":{"type":"square","frequency":{"start":440,"end":880}},"envelope":{"attack":0,"decay":0.04,"sustain":0,"release":0.012},"gain":0.16};
export const select: SoundDefinition = {"source":{"type":"square","frequency":740},"envelope":{"attack":0,"decay":0.035,"sustain":0,"release":0.01},"gain":0.15};
export const deselect: SoundDefinition = {"source":{"type":"square","frequency":554},"envelope":{"attack":0,"decay":0.03,"sustain":0,"release":0.008},"gain":0.12};
export const hover: SoundDefinition = {"source":{"type":"square","frequency":1320},"envelope":{"attack":0,"decay":0.01,"sustain":0,"release":0.004},"gain":0.06};
export const tabSwitch: SoundDefinition = {"source":{"type":"square","frequency":{"start":660,"end":880}},"envelope":{"attack":0,"decay":0.03,"sustain":0,"release":0.01},"gain":0.14};
export const expand: SoundDefinition = {"source":{"type":"square","frequency":{"start":330,"end":660}},"envelope":{"attack":0,"decay":0.06,"sustain":0,"release":0.02},"gain":0.12};
export const collapse: SoundDefinition = {"source":{"type":"square","frequency":{"start":660,"end":330}},"envelope":{"attack":0,"decay":0.06,"sustain":0,"release":0.02},"gain":0.12};
export const pageEnter: SoundDefinition = {"source":{"type":"square","frequency":{"start":440,"end":880}},"envelope":{"attack":0,"decay":0.08,"sustain":0,"release":0.025},"gain":0.1};
export const pageExit: SoundDefinition = {"source":{"type":"square","frequency":{"start":880,"end":440}},"envelope":{"attack":0,"decay":0.08,"sustain":0,"release":0.025},"gain":0.08};
export const success: SoundDefinition = {"layers":[{"source":{"type":"square","frequency":523},"envelope":{"attack":0,"decay":0.06,"sustain":0,"release":0.02},"gain":0.16},{"source":{"type":"square","frequency":659},"envelope":{"attack":0,"decay":0.06,"sustain":0,"release":0.02},"delay":0.06,"gain":0.14},{"source":{"type":"square","frequency":784},"envelope":{"attack":0,"decay":0.06,"sustain":0,"release":0.02},"delay":0.12,"gain":0.12},{"source":{"type":"square","frequency":1047},"envelope":{"attack":0,"decay":0.08,"sustain":0,"release":0.025},"delay":0.18,"gain":0.1}]};
export const error: SoundDefinition = {"layers":[{"source":{"type":"square","frequency":{"start":440,"end":220}},"envelope":{"attack":0,"decay":0.08,"sustain":0,"release":0.025},"gain":0.2},{"source":{"type":"square","frequency":{"start":330,"end":165}},"envelope":{"attack":0,"decay":0.06,"sustain":0,"release":0.02},"delay":0.04,"gain":0.14}]};
export const warning: SoundDefinition = {"layers":[{"source":{"type":"square","frequency":440},"envelope":{"attack":0,"decay":0.05,"sustain":0,"release":0.015},"gain":0.18},{"source":{"type":"square","frequency":466},"envelope":{"attack":0,"decay":0.05,"sustain":0,"release":0.015},"delay":0.012,"gain":0.14}]};
export const notification: SoundDefinition = {"layers":[{"source":{"type":"square","frequency":660},"envelope":{"attack":0,"decay":0.06,"sustain":0,"release":0.02},"gain":0.16},{"source":{"type":"square","frequency":880},"envelope":{"attack":0,"decay":0.05,"sustain":0,"release":0.015},"delay":0.07,"gain":0.14}]};
export const info: SoundDefinition = {"source":{"type":"square","frequency":880},"envelope":{"attack":0,"decay":0.06,"sustain":0,"release":0.02},"gain":0.14};
export const copy: SoundDefinition = {"layers":[{"source":{"type":"square","frequency":1047},"envelope":{"attack":0,"decay":0.02,"sustain":0,"release":0.006},"gain":0.14},{"source":{"type":"square","frequency":1320},"envelope":{"attack":0,"decay":0.02,"sustain":0,"release":0.006},"delay":0.04,"gain":0.12}]};
export const send: SoundDefinition = {"source":{"type":"square","frequency":{"start":440,"end":1320}},"envelope":{"attack":0,"decay":0.1,"sustain":0,"release":0.03},"gain":0.14};
export const _delete: SoundDefinition = {"source":{"type":"square","frequency":{"start":660,"end":165}},"envelope":{"attack":0,"decay":0.12,"sustain":0,"release":0.04},"gain":0.18};
export const undo: SoundDefinition = {"source":{"type":"square","frequency":{"start":880,"end":440}},"envelope":{"attack":0,"decay":0.06,"sustain":0,"release":0.02},"gain":0.12};
export const pop: SoundDefinition = {"source":{"type":"square","frequency":{"start":660,"end":220}},"envelope":{"attack":0,"decay":0.05,"sustain":0,"release":0.015},"gain":0.2};
export const swoosh: SoundDefinition = {"source":{"type":"square","frequency":{"start":220,"end":1760}},"envelope":{"attack":0.005,"decay":0.08,"sustain":0,"release":0.025},"gain":0.1};
export const slide: SoundDefinition = {"source":{"type":"square","frequency":{"start":440,"end":880}},"envelope":{"attack":0.003,"decay":0.06,"sustain":0,"release":0.02},"gain":0.08};

export const _patch: SoundPatch = {
  ...{"name":"Retro","author":"Raphael Salaja","version":"1.0.0","description":"8-bit square waves with chiptune character — nostalgic, pixelated UI sounds","tags":["ui","retro","8-bit","chiptune"]},
  sounds: { tap, click, "key-press": keyPress, "toggle-on": toggleOn, "toggle-off": toggleOff, checkbox, select, deselect, hover, "tab-switch": tabSwitch, expand, collapse, "page-enter": pageEnter, "page-exit": pageExit, success, error, warning, notification, info, copy, send, "delete": _delete, undo, pop, swoosh, slide },
};
