// Synths — generated by @web-kits/audio (do not edit)
// patch: Synths
import type { SoundDefinition, SoundPatch } from "@web-kits/audio";

export const bass: SoundDefinition = {"source":{"type":"sawtooth","frequency":55},"envelope":{"attack":0.01,"decay":0.3,"sustain":0.4,"release":0.2},"filter":{"type":"lowpass","frequency":800,"resonance":2},"gain":0.7};
export const subBass: SoundDefinition = {"source":{"type":"sine","frequency":40},"envelope":{"attack":0.01,"decay":0.4,"sustain":0.5,"release":0.3},"gain":0.6};
export const pad: SoundDefinition = {"source":{"type":"triangle","frequency":220},"envelope":{"attack":0.8,"decay":1,"sustain":0.7,"release":1.5},"gain":0.4};
export const drone: SoundDefinition = {"source":{"type":"sawtooth","frequency":110},"envelope":{"attack":1,"decay":1.5,"sustain":0.6,"release":2},"filter":{"type":"lowpass","frequency":600,"resonance":1},"gain":0.35};
export const lead: SoundDefinition = {"source":{"type":"sawtooth","frequency":440},"envelope":{"attack":0.01,"decay":0.2,"sustain":0.6,"release":0.3},"gain":0.5};
export const squareLead: SoundDefinition = {"source":{"type":"square","frequency":440},"envelope":{"attack":0.01,"decay":0.2,"sustain":0.5,"release":0.25},"gain":0.4};
export const electricPiano: SoundDefinition = {"source":{"type":"sine","frequency":440,"fm":{"ratio":2,"depth":300}},"envelope":{"attack":0.005,"decay":0.8,"sustain":0.1,"release":0.5},"gain":0.5};
export const organ: SoundDefinition = {"source":{"type":"sine","frequency":440,"fm":{"ratio":1,"depth":100}},"envelope":{"attack":0.01,"decay":0.1,"sustain":0.8,"release":0.2},"gain":0.45};
export const bell: SoundDefinition = {"source":{"type":"sine","frequency":880,"fm":{"ratio":3.5,"depth":500}},"envelope":{"attack":0.001,"decay":1.5,"sustain":0,"release":1},"gain":0.4};
export const chime: SoundDefinition = {"source":{"type":"sine","frequency":1047,"fm":{"ratio":2.5,"depth":400}},"envelope":{"attack":0.001,"decay":1,"sustain":0,"release":0.8},"gain":0.35};
export const arp: SoundDefinition = {"source":{"type":"square","frequency":660},"envelope":{"attack":0.005,"decay":0.1,"sustain":0.2,"release":0.15},"gain":0.35};
export const pluck: SoundDefinition = {"source":{"type":"triangle","frequency":440},"envelope":{"attack":0.002,"decay":0.6,"sustain":0.05,"release":0.4},"gain":0.5};
export const bleep: SoundDefinition = {"source":{"type":"square","frequency":{"start":880,"end":440}},"envelope":{"attack":0.001,"decay":0.15,"sustain":0,"release":0.1},"gain":0.35};
export const texture: SoundDefinition = {"source":{"type":"sawtooth","frequency":330},"envelope":{"attack":1,"decay":1.5,"sustain":0.5,"release":2},"filter":{"type":"lowpass","frequency":1200,"resonance":1},"gain":0.3};
export const noiseWhite: SoundDefinition = {"source":{"type":"noise","color":"white"},"envelope":{"attack":0.1,"decay":0.5,"sustain":0.6,"release":0.5},"gain":0.3};
export const noisePink: SoundDefinition = {"source":{"type":"noise","color":"pink"},"envelope":{"attack":0.1,"decay":0.5,"sustain":0.6,"release":0.5},"gain":0.3};
export const noiseFiltered: SoundDefinition = {"source":{"type":"noise","color":"white"},"envelope":{"attack":0.1,"decay":0.5,"sustain":0.6,"release":0.5},"filter":{"type":"bandpass","frequency":1000,"resonance":2},"gain":0.3};

export const _patch: SoundPatch = {
  ...{"name":"Synths","author":"Raphael Salaja","version":"1.0.0","description":"Synthesized instruments — bass, pads, leads, keys, bells, and arps","tags":["synths","instruments","bass","pads","leads","keys"]},
  sounds: { bass, "sub-bass": subBass, pad, drone, lead, "square-lead": squareLead, "electric-piano": electricPiano, organ, bell, chime, arp, pluck, bleep, texture, "noise-white": noiseWhite, "noise-pink": noisePink, "noise-filtered": noiseFiltered },
};
