// Core — generated by @web-kits/audio (do not edit)
// patch: Core
import { defineSound } from "@web-kits/audio";
import type { SoundPatch } from "@web-kits/audio";

export const click = defineSound({
  "source": {
    "type": "sine",
    "frequency": {
      "start": 200,
      "end": 700
    },
    "fm": {
      "ratio": 0.5,
      "depth": 80
    }
  },
  "envelope": {
    "attack": 0,
    "decay": 0.06,
    "sustain": 0,
    "release": 0.02
  },
  "gain": 0.25
});

export const tap = defineSound({
  "source": {
    "type": "sine",
    "frequency": 1300,
    "fm": {
      "ratio": 0.5,
      "depth": 100
    }
  },
  "envelope": {
    "attack": 0,
    "decay": 0.015,
    "sustain": 0,
    "release": 0.005
  },
  "gain": 0.2
});

export const keyPress = defineSound({
  "source": {
    "type": "sine",
    "frequency": 1300,
    "fm": {
      "ratio": 0.5,
      "depth": 80
    }
  },
  "envelope": {
    "attack": 0,
    "decay": 0.012,
    "sustain": 0,
    "release": 0.004
  },
  "gain": 0.18
});

export const checkbox = defineSound({
  "source": {
    "type": "sine",
    "frequency": {
      "start": 250,
      "end": 800
    },
    "fm": {
      "ratio": 0.5,
      "depth": 60
    }
  },
  "envelope": {
    "attack": 0,
    "decay": 0.05,
    "sustain": 0,
    "release": 0.015
  },
  "gain": 0.22
});

export const radio = defineSound({
  "source": {
    "type": "sine",
    "frequency": {
      "start": 300,
      "end": 900
    },
    "fm": {
      "ratio": 0.5,
      "depth": 50
    }
  },
  "envelope": {
    "attack": 0,
    "decay": 0.04,
    "sustain": 0,
    "release": 0.012
  },
  "gain": 0.2
});

export const tick = defineSound({
  "source": {
    "type": "sine",
    "frequency": 1500,
    "fm": {
      "ratio": 0.5,
      "depth": 60
    }
  },
  "envelope": {
    "attack": 0,
    "decay": 0.01,
    "sustain": 0,
    "release": 0.004
  },
  "gain": 0.15
});

export const scrollSnap = defineSound({
  "source": {
    "type": "sine",
    "frequency": 1400,
    "fm": {
      "ratio": 0.5,
      "depth": 50
    }
  },
  "envelope": {
    "attack": 0,
    "decay": 0.008,
    "sustain": 0,
    "release": 0.003
  },
  "gain": 0.08
});

export const focus = defineSound({
  "source": {
    "type": "sine",
    "frequency": 1300,
    "fm": {
      "ratio": 0.5,
      "depth": 40
    }
  },
  "envelope": {
    "attack": 0,
    "decay": 0.02,
    "sustain": 0,
    "release": 0.008
  },
  "gain": 0.06
});

export const blur = defineSound({
  "source": {
    "type": "sine",
    "frequency": 1100,
    "fm": {
      "ratio": 0.5,
      "depth": 30
    }
  },
  "envelope": {
    "attack": 0,
    "decay": 0.018,
    "sustain": 0,
    "release": 0.008
  },
  "gain": 0.04
});

export const toggleOn = defineSound({
  "layers": [
    {
      "source": {
        "type": "sine",
        "frequency": 2093
      },
      "envelope": {
        "attack": 0,
        "decay": 0.012,
        "sustain": 0,
        "release": 0.004
      },
      "gain": 0.2
    },
    {
      "source": {
        "type": "sine",
        "frequency": 3136
      },
      "envelope": {
        "attack": 0,
        "decay": 0.012,
        "sustain": 0,
        "release": 0.004
      },
      "delay": 0.025,
      "gain": 0.2
    }
  ]
});

export const toggleOff = defineSound({
  "layers": [
    {
      "source": {
        "type": "sine",
        "frequency": 3136
      },
      "envelope": {
        "attack": 0,
        "decay": 0.012,
        "sustain": 0,
        "release": 0.004
      },
      "gain": 0.2
    },
    {
      "source": {
        "type": "sine",
        "frequency": 2093
      },
      "envelope": {
        "attack": 0,
        "decay": 0.012,
        "sustain": 0,
        "release": 0.004
      },
      "delay": 0.025,
      "gain": 0.2
    }
  ]
});

export const hover = defineSound({
  "source": {
    "type": "sine",
    "frequency": 1300
  },
  "envelope": {
    "attack": 0.005,
    "decay": 0.015,
    "sustain": 0,
    "release": 0.008
  },
  "gain": 0.04
});

export const select = defineSound({
  "source": {
    "type": "sine",
    "frequency": 1400,
    "fm": {
      "ratio": 0.5,
      "depth": 60
    }
  },
  "envelope": {
    "attack": 0,
    "decay": 0.05,
    "sustain": 0,
    "release": 0.015
  },
  "gain": 0.2
});

export const deselect = defineSound({
  "source": {
    "type": "sine",
    "frequency": 1200,
    "fm": {
      "ratio": 0.5,
      "depth": 60
    }
  },
  "envelope": {
    "attack": 0,
    "decay": 0.04,
    "sustain": 0,
    "release": 0.012
  },
  "gain": 0.16
});

export const pop = defineSound({
  "source": {
    "type": "sine",
    "frequency": {
      "start": 400,
      "end": 150
    }
  },
  "envelope": {
    "attack": 0,
    "decay": 0.08,
    "sustain": 0,
    "release": 0.025
  },
  "gain": 0.25
});

export const boop = defineSound({
  "source": {
    "type": "sine",
    "frequency": {
      "start": 600,
      "end": 250
    },
    "fm": {
      "ratio": 0.5,
      "depth": 40
    }
  },
  "envelope": {
    "attack": 0,
    "decay": 0.1,
    "sustain": 0,
    "release": 0.03
  },
  "gain": 0.2
});

export const bounce = defineSound({
  "source": {
    "type": "sine",
    "frequency": {
      "start": 350,
      "end": 180
    }
  },
  "envelope": {
    "attack": 0,
    "decay": 0.12,
    "sustain": 0,
    "release": 0.04
  },
  "gain": 0.22
});

export const spring = defineSound({
  "source": {
    "type": "sine",
    "frequency": {
      "start": 400,
      "end": 900
    },
    "fm": {
      "ratio": 0.5,
      "depth": 50
    }
  },
  "envelope": {
    "attack": 0,
    "decay": 0.15,
    "sustain": 0.03,
    "release": 0.05
  },
  "gain": 0.18
});

export const expand = defineSound({
  "source": {
    "type": "sine",
    "frequency": {
      "start": 500,
      "end": 700
    }
  },
  "envelope": {
    "attack": 0.003,
    "decay": 0.1,
    "sustain": 0.02,
    "release": 0.04
  },
  "gain": 0.12
});

export const collapse = defineSound({
  "source": {
    "type": "sine",
    "frequency": {
      "start": 700,
      "end": 500
    }
  },
  "envelope": {
    "attack": 0.003,
    "decay": 0.1,
    "sustain": 0.02,
    "release": 0.04
  },
  "gain": 0.12
});

export const success = defineSound({
  "layers": [
    {
      "source": {
        "type": "sine",
        "frequency": 523
      },
      "envelope": {
        "attack": 0.003,
        "decay": 0.3,
        "sustain": 0.06,
        "release": 0.1
      },
      "gain": 0.16
    },
    {
      "source": {
        "type": "sine",
        "frequency": 659
      },
      "envelope": {
        "attack": 0.003,
        "decay": 0.28,
        "sustain": 0.05,
        "release": 0.1
      },
      "delay": 0.07,
      "gain": 0.14
    },
    {
      "source": {
        "type": "sine",
        "frequency": {
          "start": 784,
          "end": 880
        }
      },
      "envelope": {
        "attack": 0.003,
        "decay": 0.32,
        "sustain": 0.06,
        "release": 0.12
      },
      "delay": 0.14,
      "gain": 0.15
    }
  ]
});

export const complete = defineSound({
  "layers": [
    {
      "source": {
        "type": "sine",
        "frequency": 523
      },
      "envelope": {
        "attack": 0.003,
        "decay": 0.35,
        "sustain": 0.05,
        "release": 0.1
      },
      "gain": 0.15
    },
    {
      "source": {
        "type": "sine",
        "frequency": 659
      },
      "envelope": {
        "attack": 0.003,
        "decay": 0.35,
        "sustain": 0.05,
        "release": 0.1
      },
      "delay": 0.015,
      "gain": 0.13
    },
    {
      "source": {
        "type": "sine",
        "frequency": 784
      },
      "envelope": {
        "attack": 0.003,
        "decay": 0.35,
        "sustain": 0.05,
        "release": 0.1
      },
      "delay": 0.03,
      "gain": 0.12
    },
    {
      "source": {
        "type": "sine",
        "frequency": {
          "start": 1046,
          "end": 1175
        }
      },
      "envelope": {
        "attack": 0.003,
        "decay": 0.3,
        "sustain": 0.04,
        "release": 0.12
      },
      "delay": 0.045,
      "gain": 0.1
    }
  ]
});

export const levelUp = defineSound({
  "layers": [
    {
      "source": {
        "type": "sine",
        "frequency": 440
      },
      "envelope": {
        "attack": 0.003,
        "decay": 0.25,
        "sustain": 0.06,
        "release": 0.1
      },
      "gain": 0.15
    },
    {
      "source": {
        "type": "sine",
        "frequency": 554
      },
      "envelope": {
        "attack": 0.003,
        "decay": 0.25,
        "sustain": 0.05,
        "release": 0.1
      },
      "delay": 0.07,
      "gain": 0.14
    },
    {
      "source": {
        "type": "sine",
        "frequency": 660
      },
      "envelope": {
        "attack": 0.003,
        "decay": 0.28,
        "sustain": 0.05,
        "release": 0.1
      },
      "delay": 0.14,
      "gain": 0.13
    },
    {
      "source": {
        "type": "sine",
        "frequency": {
          "start": 880,
          "end": 990
        }
      },
      "envelope": {
        "attack": 0.003,
        "decay": 0.22,
        "sustain": 0.04,
        "release": 0.12
      },
      "delay": 0.21,
      "gain": 0.08
    }
  ]
});

export const confetti = defineSound({
  "layers": [
    {
      "source": {
        "type": "sine",
        "frequency": 523
      },
      "envelope": {
        "attack": 0.002,
        "decay": 0.18,
        "sustain": 0.04,
        "release": 0.08
      },
      "gain": 0.14
    },
    {
      "source": {
        "type": "sine",
        "frequency": 659
      },
      "envelope": {
        "attack": 0.002,
        "decay": 0.18,
        "sustain": 0.04,
        "release": 0.08
      },
      "delay": 0.06,
      "gain": 0.14
    },
    {
      "source": {
        "type": "sine",
        "frequency": 784
      },
      "envelope": {
        "attack": 0.002,
        "decay": 0.18,
        "sustain": 0.03,
        "release": 0.08
      },
      "delay": 0.12,
      "gain": 0.12
    },
    {
      "source": {
        "type": "sine",
        "frequency": {
          "start": 1047,
          "end": 1175
        }
      },
      "envelope": {
        "attack": 0.002,
        "decay": 0.2,
        "sustain": 0.03,
        "release": 0.1
      },
      "delay": 0.18,
      "gain": 0.1
    }
  ]
});

export const save = defineSound({
  "layers": [
    {
      "source": {
        "type": "sine",
        "frequency": {
          "start": 880,
          "end": 1046
        }
      },
      "envelope": {
        "attack": 0,
        "decay": 0.1,
        "sustain": 0.03,
        "release": 0.04
      },
      "gain": 0.14
    },
    {
      "source": {
        "type": "sine",
        "frequency": {
          "start": 1046,
          "end": 1175
        }
      },
      "envelope": {
        "attack": 0,
        "decay": 0.1,
        "sustain": 0.02,
        "release": 0.04
      },
      "delay": 0.08,
      "gain": 0.1
    }
  ]
});

export const ding = defineSound({
  "source": {
    "type": "sine",
    "frequency": 880,
    "fm": {
      "ratio": 3.5,
      "depth": 300
    }
  },
  "envelope": {
    "attack": 0,
    "decay": 0.6,
    "sustain": 0.04,
    "release": 0.25
  },
  "effects": [
    {
      "type": "reverb",
      "decay": 0.8,
      "damping": 0.6,
      "mix": 0.15
    }
  ],
  "gain": 0.18
});

export const notification = defineSound({
  "layers": [
    {
      "source": {
        "type": "sine",
        "frequency": 780,
        "fm": {
          "ratio": 1.5,
          "depth": 150
        }
      },
      "envelope": {
        "attack": 0,
        "decay": 0.4,
        "sustain": 0.04,
        "release": 0.15
      },
      "effects": [
        {
          "type": "reverb",
          "decay": 0.6,
          "damping": 0.6,
          "mix": 0.12
        }
      ],
      "gain": 0.16
    },
    {
      "source": {
        "type": "sine",
        "frequency": 1170,
        "fm": {
          "ratio": 1.5,
          "depth": 120
        }
      },
      "envelope": {
        "attack": 0,
        "decay": 0.35,
        "sustain": 0.03,
        "release": 0.15
      },
      "delay": 0.1,
      "effects": [
        {
          "type": "reverb",
          "decay": 0.6,
          "damping": 0.6,
          "mix": 0.12
        }
      ],
      "gain": 0.14
    }
  ]
});

export const mention = defineSound({
  "source": {
    "type": "sine",
    "frequency": 660,
    "fm": {
      "ratio": 2.5,
      "depth": 150
    }
  },
  "envelope": {
    "attack": 0.003,
    "decay": 0.5,
    "sustain": 0.05,
    "release": 0.2
  },
  "effects": [
    {
      "type": "reverb",
      "decay": 0.6,
      "damping": 0.5,
      "mix": 0.1
    }
  ],
  "gain": 0.14
});

export const badge = defineSound({
  "source": {
    "type": "sine",
    "frequency": 1100,
    "fm": {
      "ratio": 2.76,
      "depth": 350
    }
  },
  "envelope": {
    "attack": 0,
    "decay": 0.35,
    "sustain": 0.04,
    "release": 0.15
  },
  "effects": [
    {
      "type": "reverb",
      "decay": 0.5,
      "damping": 0.6,
      "mix": 0.1
    }
  ],
  "gain": 0.16
});

export const info = defineSound({
  "source": {
    "type": "sine",
    "frequency": 880,
    "fm": {
      "ratio": 2,
      "depth": 120
    }
  },
  "envelope": {
    "attack": 0.003,
    "decay": 0.3,
    "sustain": 0.04,
    "release": 0.12
  },
  "gain": 0.14
});

export const sparkle = defineSound({
  "layers": [
    {
      "source": {
        "type": "sine",
        "frequency": 1047,
        "detune": 7,
        "fm": {
          "ratio": 3.5,
          "depth": 200
        }
      },
      "envelope": {
        "attack": 0,
        "decay": 0.4,
        "sustain": 0.04,
        "release": 0.18
      },
      "effects": [
        {
          "type": "reverb",
          "decay": 0.8,
          "damping": 0.5,
          "mix": 0.15
        }
      ],
      "gain": 0.12
    },
    {
      "source": {
        "type": "sine",
        "frequency": 1050,
        "fm": {
          "ratio": 3.5,
          "depth": 180
        }
      },
      "envelope": {
        "attack": 0,
        "decay": 0.38,
        "sustain": 0.03,
        "release": 0.18
      },
      "gain": 0.08
    }
  ]
});

export const star = defineSound({
  "source": {
    "type": "sine",
    "frequency": 880,
    "fm": {
      "ratio": 2.76,
      "depth": 250
    }
  },
  "envelope": {
    "attack": 0,
    "decay": 0.4,
    "sustain": 0.04,
    "release": 0.18
  },
  "effects": [
    {
      "type": "reverb",
      "decay": 0.6,
      "damping": 0.5,
      "mix": 0.12
    }
  ],
  "gain": 0.14
});

export const error = defineSound({
  "layers": [
    {
      "source": {
        "type": "sawtooth",
        "frequency": {
          "start": 320,
          "end": 140
        }
      },
      "filter": {
        "type": "lowpass",
        "frequency": 1200
      },
      "envelope": {
        "attack": 0,
        "decay": 0.25,
        "sustain": 0,
        "release": 0.08
      },
      "gain": 0.22
    },
    {
      "source": {
        "type": "square",
        "frequency": {
          "start": 180,
          "end": 80
        }
      },
      "filter": {
        "type": "lowpass",
        "frequency": 800
      },
      "envelope": {
        "attack": 0,
        "decay": 0.2,
        "sustain": 0,
        "release": 0.06
      },
      "delay": 0.03,
      "gain": 0.12
    }
  ]
});

export const _delete = defineSound({
  "layers": [
    {
      "source": {
        "type": "sawtooth",
        "frequency": {
          "start": 300,
          "end": 100
        }
      },
      "filter": {
        "type": "lowpass",
        "frequency": 800
      },
      "envelope": {
        "attack": 0,
        "decay": 0.3,
        "sustain": 0,
        "release": 0.08
      },
      "gain": 0.18
    },
    {
      "source": {
        "type": "square",
        "frequency": {
          "start": 200,
          "end": 60
        }
      },
      "filter": {
        "type": "lowpass",
        "frequency": 600
      },
      "envelope": {
        "attack": 0,
        "decay": 0.25,
        "sustain": 0,
        "release": 0.06
      },
      "delay": 0.02,
      "gain": 0.1
    }
  ]
});

export const warning = defineSound({
  "layers": [
    {
      "source": {
        "type": "triangle",
        "frequency": 440
      },
      "envelope": {
        "attack": 0,
        "decay": 0.18,
        "sustain": 0.06,
        "release": 0.06
      },
      "gain": 0.2
    },
    {
      "source": {
        "type": "triangle",
        "frequency": 466
      },
      "envelope": {
        "attack": 0,
        "decay": 0.18,
        "sustain": 0.06,
        "release": 0.06
      },
      "delay": 0.01,
      "gain": 0.15
    }
  ]
});

export const swoosh = defineSound({
  "source": {
    "type": "noise",
    "color": "white"
  },
  "filter": {
    "type": "bandpass",
    "frequency": 300,
    "resonance": 1.8,
    "envelope": {
      "attack": 0.01,
      "peak": 4000,
      "decay": 0.08
    }
  },
  "envelope": {
    "attack": 0.01,
    "decay": 0.12,
    "sustain": 0,
    "release": 0.04
  },
  "gain": 0.12
});

export const whoosh = defineSound({
  "source": {
    "type": "noise",
    "color": "white"
  },
  "filter": {
    "type": "bandpass",
    "frequency": 300,
    "resonance": 1.5,
    "envelope": {
      "attack": 0.04,
      "peak": 4000,
      "decay": 0.16
    }
  },
  "envelope": {
    "attack": 0.02,
    "decay": 0.25,
    "sustain": 0,
    "release": 0.08
  },
  "gain": 0.15
});

export const pageEnter = defineSound({
  "source": {
    "type": "noise",
    "color": "white"
  },
  "filter": {
    "type": "bandpass",
    "frequency": 400,
    "resonance": 1.2,
    "envelope": {
      "attack": 0.03,
      "peak": 3000,
      "decay": 0.15
    }
  },
  "envelope": {
    "attack": 0.02,
    "decay": 0.2,
    "sustain": 0,
    "release": 0.06
  },
  "gain": 0.08
});

export const pageExit = defineSound({
  "source": {
    "type": "noise",
    "color": "pink"
  },
  "filter": {
    "type": "bandpass",
    "frequency": 2500,
    "resonance": 1.2,
    "envelope": {
      "decay": 0.18,
      "peak": 400
    }
  },
  "envelope": {
    "attack": 0.01,
    "decay": 0.2,
    "sustain": 0,
    "release": 0.06
  },
  "gain": 0.07
});

export const tabSwitch = defineSound({
  "source": {
    "type": "sine",
    "frequency": {
      "start": 1100,
      "end": 1500
    },
    "fm": {
      "ratio": 0.5,
      "depth": 50
    }
  },
  "envelope": {
    "attack": 0,
    "decay": 0.05,
    "sustain": 0,
    "release": 0.015
  },
  "gain": 0.18
});

export const drawerOpen = defineSound({
  "source": {
    "type": "sine",
    "frequency": {
      "start": 350,
      "end": 1000
    }
  },
  "envelope": {
    "attack": 0,
    "decay": 0.1,
    "sustain": 0,
    "release": 0.03
  },
  "gain": 0.08
});

export const drawerClose = defineSound({
  "source": {
    "type": "sine",
    "frequency": {
      "start": 800,
      "end": 350
    }
  },
  "envelope": {
    "attack": 0,
    "decay": 0.1,
    "sustain": 0,
    "release": 0.03
  },
  "gain": 0.06
});

export const modalOpen = defineSound({
  "source": {
    "type": "sine",
    "frequency": {
      "start": 430,
      "end": 1400
    }
  },
  "envelope": {
    "attack": 0,
    "decay": 0.08,
    "sustain": 0,
    "release": 0.025
  },
  "gain": 0.1
});

export const modalClose = defineSound({
  "source": {
    "type": "sine",
    "frequency": {
      "start": 730,
      "end": 430
    }
  },
  "envelope": {
    "attack": 0,
    "decay": 0.08,
    "sustain": 0,
    "release": 0.025
  },
  "gain": 0.08
});

export const dropdownOpen = defineSound({
  "source": {
    "type": "sine",
    "frequency": {
      "start": 500,
      "end": 1200
    }
  },
  "envelope": {
    "attack": 0,
    "decay": 0.06,
    "sustain": 0,
    "release": 0.02
  },
  "gain": 0.07
});

export const dropdownClose = defineSound({
  "source": {
    "type": "sine",
    "frequency": {
      "start": 900,
      "end": 500
    }
  },
  "envelope": {
    "attack": 0,
    "decay": 0.06,
    "sustain": 0,
    "release": 0.02
  },
  "gain": 0.05
});

export const slide = defineSound({
  "source": {
    "type": "noise",
    "color": "white"
  },
  "filter": {
    "type": "bandpass",
    "frequency": 500,
    "resonance": 1,
    "envelope": {
      "attack": 0.02,
      "peak": 3000,
      "decay": 0.12
    }
  },
  "envelope": {
    "attack": 0.01,
    "decay": 0.15,
    "sustain": 0,
    "release": 0.05
  },
  "gain": 0.07
});

export const slideUp = defineSound({
  "source": {
    "type": "noise",
    "color": "white"
  },
  "filter": {
    "type": "bandpass",
    "frequency": 500,
    "resonance": 1,
    "envelope": {
      "attack": 0.02,
      "peak": 3500,
      "decay": 0.12
    }
  },
  "envelope": {
    "attack": 0.01,
    "decay": 0.15,
    "sustain": 0,
    "release": 0.05
  },
  "gain": 0.07
});

export const slideDown = defineSound({
  "source": {
    "type": "noise",
    "color": "pink"
  },
  "filter": {
    "type": "bandpass",
    "frequency": 2500,
    "resonance": 1,
    "envelope": {
      "decay": 0.12,
      "peak": 500
    }
  },
  "envelope": {
    "attack": 0.01,
    "decay": 0.15,
    "sustain": 0,
    "release": 0.05
  },
  "gain": 0.06
});

export const copy = defineSound({
  "layers": [
    {
      "source": {
        "type": "sine",
        "frequency": 1200
      },
      "envelope": {
        "attack": 0,
        "decay": 0.015,
        "sustain": 0,
        "release": 0.006
      },
      "gain": 0.16
    },
    {
      "source": {
        "type": "sine",
        "frequency": 1400
      },
      "envelope": {
        "attack": 0,
        "decay": 0.015,
        "sustain": 0,
        "release": 0.006
      },
      "delay": 0.04,
      "gain": 0.14
    }
  ]
});

export const send = defineSound({
  "source": {
    "type": "sine",
    "frequency": {
      "start": 500,
      "end": 1200
    }
  },
  "envelope": {
    "attack": 0,
    "decay": 0.15,
    "sustain": 0,
    "release": 0.04
  },
  "gain": 0.16
});

export const receive = defineSound({
  "source": {
    "type": "sine",
    "frequency": {
      "start": 1200,
      "end": 700
    }
  },
  "envelope": {
    "attack": 0,
    "decay": 0.12,
    "sustain": 0.02,
    "release": 0.04
  },
  "gain": 0.12
});

export const command = defineSound({
  "layers": [
    {
      "source": {
        "type": "sine",
        "frequency": {
          "start": 600,
          "end": 900
        }
      },
      "envelope": {
        "attack": 0,
        "decay": 0.05,
        "sustain": 0,
        "release": 0.015
      },
      "gain": 0.18
    },
    {
      "source": {
        "type": "sine",
        "frequency": {
          "start": 900,
          "end": 1100
        }
      },
      "envelope": {
        "attack": 0,
        "decay": 0.04,
        "sustain": 0,
        "release": 0.012
      },
      "delay": 0.04,
      "gain": 0.12
    }
  ]
});

export const escape = defineSound({
  "layers": [
    {
      "source": {
        "type": "sine",
        "frequency": {
          "start": 900,
          "end": 600
        }
      },
      "envelope": {
        "attack": 0,
        "decay": 0.05,
        "sustain": 0,
        "release": 0.015
      },
      "gain": 0.16
    },
    {
      "source": {
        "type": "sine",
        "frequency": {
          "start": 700,
          "end": 500
        }
      },
      "envelope": {
        "attack": 0,
        "decay": 0.04,
        "sustain": 0,
        "release": 0.012
      },
      "delay": 0.03,
      "gain": 0.1
    }
  ]
});

export const undo = defineSound({
  "source": {
    "type": "sine",
    "frequency": {
      "start": 900,
      "end": 600
    }
  },
  "envelope": {
    "attack": 0,
    "decay": 0.12,
    "sustain": 0.02,
    "release": 0.04
  },
  "gain": 0.14
});

export const archive = defineSound({
  "source": {
    "type": "sine",
    "frequency": {
      "start": 800,
      "end": 550
    }
  },
  "envelope": {
    "attack": 0.003,
    "decay": 0.15,
    "sustain": 0.02,
    "release": 0.05
  },
  "gain": 0.12
});

export const sync = defineSound({
  "layers": [
    {
      "source": {
        "type": "sine",
        "frequency": 523
      },
      "envelope": {
        "attack": 0,
        "decay": 0.015,
        "sustain": 0,
        "release": 0.005
      },
      "gain": 0.14
    },
    {
      "source": {
        "type": "sine",
        "frequency": 784
      },
      "envelope": {
        "attack": 0,
        "decay": 0.015,
        "sustain": 0,
        "release": 0.005
      },
      "delay": 0.04,
      "gain": 0.12
    }
  ]
});

export const heart = defineSound({
  "layers": [
    {
      "source": {
        "type": "sine",
        "frequency": {
          "start": 500,
          "end": 300
        }
      },
      "envelope": {
        "attack": 0,
        "decay": 0.1,
        "sustain": 0,
        "release": 0.04
      },
      "gain": 0.16
    },
    {
      "source": {
        "type": "sine",
        "frequency": 523,
        "fm": {
          "ratio": 2.5,
          "depth": 100
        }
      },
      "envelope": {
        "attack": 0.008,
        "decay": 0.25,
        "sustain": 0.04,
        "release": 0.1
      },
      "gain": 0.1
    }
  ]
});

export const streak = defineSound({
  "layers": [
    {
      "source": {
        "type": "sine",
        "frequency": {
          "start": 523,
          "end": 784
        }
      },
      "envelope": {
        "attack": 0,
        "decay": 0.12,
        "sustain": 0.02,
        "release": 0.05
      },
      "gain": 0.16
    },
    {
      "source": {
        "type": "sine",
        "frequency": {
          "start": 526,
          "end": 787
        },
        "fm": {
          "ratio": 2.5,
          "depth": 100
        }
      },
      "envelope": {
        "attack": 0,
        "decay": 0.11,
        "sustain": 0.01,
        "release": 0.05
      },
      "gain": 0.08
    }
  ]
});

export const loadingStart = defineSound({
  "source": {
    "type": "sine",
    "frequency": {
      "start": 500,
      "end": 700
    }
  },
  "envelope": {
    "attack": 0.008,
    "decay": 0.12,
    "sustain": 0.02,
    "release": 0.05
  },
  "gain": 0.08
});

export const loadingEnd = defineSound({
  "layers": [
    {
      "source": {
        "type": "sine",
        "frequency": {
          "start": 700,
          "end": 880
        }
      },
      "envelope": {
        "attack": 0,
        "decay": 0.1,
        "sustain": 0.02,
        "release": 0.04
      },
      "gain": 0.1
    },
    {
      "source": {
        "type": "sine",
        "frequency": {
          "start": 880,
          "end": 1046
        }
      },
      "envelope": {
        "attack": 0,
        "decay": 0.08,
        "sustain": 0.01,
        "release": 0.04
      },
      "delay": 0.06,
      "gain": 0.08
    }
  ]
});

export const progressTick = defineSound({
  "source": {
    "type": "sine",
    "frequency": 1400,
    "fm": {
      "ratio": 0.5,
      "depth": 50
    }
  },
  "envelope": {
    "attack": 0,
    "decay": 0.01,
    "sustain": 0,
    "release": 0.004
  },
  "gain": 0.1
});

export const _patch: SoundPatch = {
  "$schema": "../packages/legato/schemas/pack.schema.json",
  "name": "Core",
  "author": "Raphael Salaja",
  "version": "3.1.0",
  "description": "Essential UI interaction sounds — clicks, toggles, pops, notifications, transitions, and more",
  "tags": [
    "ui",
    "interactions",
    "feedback",
    "transitions",
    "notifications"
  ],
  "sounds": {
    "click": {
      "source": {
        "type": "sine",
        "frequency": {
          "start": 200,
          "end": 700
        },
        "fm": {
          "ratio": 0.5,
          "depth": 80
        }
      },
      "envelope": {
        "attack": 0,
        "decay": 0.06,
        "sustain": 0,
        "release": 0.02
      },
      "gain": 0.25
    },
    "tap": {
      "source": {
        "type": "sine",
        "frequency": 1300,
        "fm": {
          "ratio": 0.5,
          "depth": 100
        }
      },
      "envelope": {
        "attack": 0,
        "decay": 0.015,
        "sustain": 0,
        "release": 0.005
      },
      "gain": 0.2
    },
    "key-press": {
      "source": {
        "type": "sine",
        "frequency": 1300,
        "fm": {
          "ratio": 0.5,
          "depth": 80
        }
      },
      "envelope": {
        "attack": 0,
        "decay": 0.012,
        "sustain": 0,
        "release": 0.004
      },
      "gain": 0.18
    },
    "checkbox": {
      "source": {
        "type": "sine",
        "frequency": {
          "start": 250,
          "end": 800
        },
        "fm": {
          "ratio": 0.5,
          "depth": 60
        }
      },
      "envelope": {
        "attack": 0,
        "decay": 0.05,
        "sustain": 0,
        "release": 0.015
      },
      "gain": 0.22
    },
    "radio": {
      "source": {
        "type": "sine",
        "frequency": {
          "start": 300,
          "end": 900
        },
        "fm": {
          "ratio": 0.5,
          "depth": 50
        }
      },
      "envelope": {
        "attack": 0,
        "decay": 0.04,
        "sustain": 0,
        "release": 0.012
      },
      "gain": 0.2
    },
    "tick": {
      "source": {
        "type": "sine",
        "frequency": 1500,
        "fm": {
          "ratio": 0.5,
          "depth": 60
        }
      },
      "envelope": {
        "attack": 0,
        "decay": 0.01,
        "sustain": 0,
        "release": 0.004
      },
      "gain": 0.15
    },
    "scroll-snap": {
      "source": {
        "type": "sine",
        "frequency": 1400,
        "fm": {
          "ratio": 0.5,
          "depth": 50
        }
      },
      "envelope": {
        "attack": 0,
        "decay": 0.008,
        "sustain": 0,
        "release": 0.003
      },
      "gain": 0.08
    },
    "focus": {
      "source": {
        "type": "sine",
        "frequency": 1300,
        "fm": {
          "ratio": 0.5,
          "depth": 40
        }
      },
      "envelope": {
        "attack": 0,
        "decay": 0.02,
        "sustain": 0,
        "release": 0.008
      },
      "gain": 0.06
    },
    "blur": {
      "source": {
        "type": "sine",
        "frequency": 1100,
        "fm": {
          "ratio": 0.5,
          "depth": 30
        }
      },
      "envelope": {
        "attack": 0,
        "decay": 0.018,
        "sustain": 0,
        "release": 0.008
      },
      "gain": 0.04
    },
    "toggle-on": {
      "layers": [
        {
          "source": {
            "type": "sine",
            "frequency": 2093
          },
          "envelope": {
            "attack": 0,
            "decay": 0.012,
            "sustain": 0,
            "release": 0.004
          },
          "gain": 0.2
        },
        {
          "source": {
            "type": "sine",
            "frequency": 3136
          },
          "envelope": {
            "attack": 0,
            "decay": 0.012,
            "sustain": 0,
            "release": 0.004
          },
          "delay": 0.025,
          "gain": 0.2
        }
      ]
    },
    "toggle-off": {
      "layers": [
        {
          "source": {
            "type": "sine",
            "frequency": 3136
          },
          "envelope": {
            "attack": 0,
            "decay": 0.012,
            "sustain": 0,
            "release": 0.004
          },
          "gain": 0.2
        },
        {
          "source": {
            "type": "sine",
            "frequency": 2093
          },
          "envelope": {
            "attack": 0,
            "decay": 0.012,
            "sustain": 0,
            "release": 0.004
          },
          "delay": 0.025,
          "gain": 0.2
        }
      ]
    },
    "hover": {
      "source": {
        "type": "sine",
        "frequency": 1300
      },
      "envelope": {
        "attack": 0.005,
        "decay": 0.015,
        "sustain": 0,
        "release": 0.008
      },
      "gain": 0.04
    },
    "select": {
      "source": {
        "type": "sine",
        "frequency": 1400,
        "fm": {
          "ratio": 0.5,
          "depth": 60
        }
      },
      "envelope": {
        "attack": 0,
        "decay": 0.05,
        "sustain": 0,
        "release": 0.015
      },
      "gain": 0.2
    },
    "deselect": {
      "source": {
        "type": "sine",
        "frequency": 1200,
        "fm": {
          "ratio": 0.5,
          "depth": 60
        }
      },
      "envelope": {
        "attack": 0,
        "decay": 0.04,
        "sustain": 0,
        "release": 0.012
      },
      "gain": 0.16
    },
    "pop": {
      "source": {
        "type": "sine",
        "frequency": {
          "start": 400,
          "end": 150
        }
      },
      "envelope": {
        "attack": 0,
        "decay": 0.08,
        "sustain": 0,
        "release": 0.025
      },
      "gain": 0.25
    },
    "boop": {
      "source": {
        "type": "sine",
        "frequency": {
          "start": 600,
          "end": 250
        },
        "fm": {
          "ratio": 0.5,
          "depth": 40
        }
      },
      "envelope": {
        "attack": 0,
        "decay": 0.1,
        "sustain": 0,
        "release": 0.03
      },
      "gain": 0.2
    },
    "bounce": {
      "source": {
        "type": "sine",
        "frequency": {
          "start": 350,
          "end": 180
        }
      },
      "envelope": {
        "attack": 0,
        "decay": 0.12,
        "sustain": 0,
        "release": 0.04
      },
      "gain": 0.22
    },
    "spring": {
      "source": {
        "type": "sine",
        "frequency": {
          "start": 400,
          "end": 900
        },
        "fm": {
          "ratio": 0.5,
          "depth": 50
        }
      },
      "envelope": {
        "attack": 0,
        "decay": 0.15,
        "sustain": 0.03,
        "release": 0.05
      },
      "gain": 0.18
    },
    "expand": {
      "source": {
        "type": "sine",
        "frequency": {
          "start": 500,
          "end": 700
        }
      },
      "envelope": {
        "attack": 0.003,
        "decay": 0.1,
        "sustain": 0.02,
        "release": 0.04
      },
      "gain": 0.12
    },
    "collapse": {
      "source": {
        "type": "sine",
        "frequency": {
          "start": 700,
          "end": 500
        }
      },
      "envelope": {
        "attack": 0.003,
        "decay": 0.1,
        "sustain": 0.02,
        "release": 0.04
      },
      "gain": 0.12
    },
    "success": {
      "layers": [
        {
          "source": {
            "type": "sine",
            "frequency": 523
          },
          "envelope": {
            "attack": 0.003,
            "decay": 0.3,
            "sustain": 0.06,
            "release": 0.1
          },
          "gain": 0.16
        },
        {
          "source": {
            "type": "sine",
            "frequency": 659
          },
          "envelope": {
            "attack": 0.003,
            "decay": 0.28,
            "sustain": 0.05,
            "release": 0.1
          },
          "delay": 0.07,
          "gain": 0.14
        },
        {
          "source": {
            "type": "sine",
            "frequency": {
              "start": 784,
              "end": 880
            }
          },
          "envelope": {
            "attack": 0.003,
            "decay": 0.32,
            "sustain": 0.06,
            "release": 0.12
          },
          "delay": 0.14,
          "gain": 0.15
        }
      ]
    },
    "complete": {
      "layers": [
        {
          "source": {
            "type": "sine",
            "frequency": 523
          },
          "envelope": {
            "attack": 0.003,
            "decay": 0.35,
            "sustain": 0.05,
            "release": 0.1
          },
          "gain": 0.15
        },
        {
          "source": {
            "type": "sine",
            "frequency": 659
          },
          "envelope": {
            "attack": 0.003,
            "decay": 0.35,
            "sustain": 0.05,
            "release": 0.1
          },
          "delay": 0.015,
          "gain": 0.13
        },
        {
          "source": {
            "type": "sine",
            "frequency": 784
          },
          "envelope": {
            "attack": 0.003,
            "decay": 0.35,
            "sustain": 0.05,
            "release": 0.1
          },
          "delay": 0.03,
          "gain": 0.12
        },
        {
          "source": {
            "type": "sine",
            "frequency": {
              "start": 1046,
              "end": 1175
            }
          },
          "envelope": {
            "attack": 0.003,
            "decay": 0.3,
            "sustain": 0.04,
            "release": 0.12
          },
          "delay": 0.045,
          "gain": 0.1
        }
      ]
    },
    "level-up": {
      "layers": [
        {
          "source": {
            "type": "sine",
            "frequency": 440
          },
          "envelope": {
            "attack": 0.003,
            "decay": 0.25,
            "sustain": 0.06,
            "release": 0.1
          },
          "gain": 0.15
        },
        {
          "source": {
            "type": "sine",
            "frequency": 554
          },
          "envelope": {
            "attack": 0.003,
            "decay": 0.25,
            "sustain": 0.05,
            "release": 0.1
          },
          "delay": 0.07,
          "gain": 0.14
        },
        {
          "source": {
            "type": "sine",
            "frequency": 660
          },
          "envelope": {
            "attack": 0.003,
            "decay": 0.28,
            "sustain": 0.05,
            "release": 0.1
          },
          "delay": 0.14,
          "gain": 0.13
        },
        {
          "source": {
            "type": "sine",
            "frequency": {
              "start": 880,
              "end": 990
            }
          },
          "envelope": {
            "attack": 0.003,
            "decay": 0.22,
            "sustain": 0.04,
            "release": 0.12
          },
          "delay": 0.21,
          "gain": 0.08
        }
      ]
    },
    "confetti": {
      "layers": [
        {
          "source": {
            "type": "sine",
            "frequency": 523
          },
          "envelope": {
            "attack": 0.002,
            "decay": 0.18,
            "sustain": 0.04,
            "release": 0.08
          },
          "gain": 0.14
        },
        {
          "source": {
            "type": "sine",
            "frequency": 659
          },
          "envelope": {
            "attack": 0.002,
            "decay": 0.18,
            "sustain": 0.04,
            "release": 0.08
          },
          "delay": 0.06,
          "gain": 0.14
        },
        {
          "source": {
            "type": "sine",
            "frequency": 784
          },
          "envelope": {
            "attack": 0.002,
            "decay": 0.18,
            "sustain": 0.03,
            "release": 0.08
          },
          "delay": 0.12,
          "gain": 0.12
        },
        {
          "source": {
            "type": "sine",
            "frequency": {
              "start": 1047,
              "end": 1175
            }
          },
          "envelope": {
            "attack": 0.002,
            "decay": 0.2,
            "sustain": 0.03,
            "release": 0.1
          },
          "delay": 0.18,
          "gain": 0.1
        }
      ]
    },
    "save": {
      "layers": [
        {
          "source": {
            "type": "sine",
            "frequency": {
              "start": 880,
              "end": 1046
            }
          },
          "envelope": {
            "attack": 0,
            "decay": 0.1,
            "sustain": 0.03,
            "release": 0.04
          },
          "gain": 0.14
        },
        {
          "source": {
            "type": "sine",
            "frequency": {
              "start": 1046,
              "end": 1175
            }
          },
          "envelope": {
            "attack": 0,
            "decay": 0.1,
            "sustain": 0.02,
            "release": 0.04
          },
          "delay": 0.08,
          "gain": 0.1
        }
      ]
    },
    "ding": {
      "source": {
        "type": "sine",
        "frequency": 880,
        "fm": {
          "ratio": 3.5,
          "depth": 300
        }
      },
      "envelope": {
        "attack": 0,
        "decay": 0.6,
        "sustain": 0.04,
        "release": 0.25
      },
      "effects": [
        {
          "type": "reverb",
          "decay": 0.8,
          "damping": 0.6,
          "mix": 0.15
        }
      ],
      "gain": 0.18
    },
    "notification": {
      "layers": [
        {
          "source": {
            "type": "sine",
            "frequency": 780,
            "fm": {
              "ratio": 1.5,
              "depth": 150
            }
          },
          "envelope": {
            "attack": 0,
            "decay": 0.4,
            "sustain": 0.04,
            "release": 0.15
          },
          "effects": [
            {
              "type": "reverb",
              "decay": 0.6,
              "damping": 0.6,
              "mix": 0.12
            }
          ],
          "gain": 0.16
        },
        {
          "source": {
            "type": "sine",
            "frequency": 1170,
            "fm": {
              "ratio": 1.5,
              "depth": 120
            }
          },
          "envelope": {
            "attack": 0,
            "decay": 0.35,
            "sustain": 0.03,
            "release": 0.15
          },
          "delay": 0.1,
          "effects": [
            {
              "type": "reverb",
              "decay": 0.6,
              "damping": 0.6,
              "mix": 0.12
            }
          ],
          "gain": 0.14
        }
      ]
    },
    "mention": {
      "source": {
        "type": "sine",
        "frequency": 660,
        "fm": {
          "ratio": 2.5,
          "depth": 150
        }
      },
      "envelope": {
        "attack": 0.003,
        "decay": 0.5,
        "sustain": 0.05,
        "release": 0.2
      },
      "effects": [
        {
          "type": "reverb",
          "decay": 0.6,
          "damping": 0.5,
          "mix": 0.1
        }
      ],
      "gain": 0.14
    },
    "badge": {
      "source": {
        "type": "sine",
        "frequency": 1100,
        "fm": {
          "ratio": 2.76,
          "depth": 350
        }
      },
      "envelope": {
        "attack": 0,
        "decay": 0.35,
        "sustain": 0.04,
        "release": 0.15
      },
      "effects": [
        {
          "type": "reverb",
          "decay": 0.5,
          "damping": 0.6,
          "mix": 0.1
        }
      ],
      "gain": 0.16
    },
    "info": {
      "source": {
        "type": "sine",
        "frequency": 880,
        "fm": {
          "ratio": 2,
          "depth": 120
        }
      },
      "envelope": {
        "attack": 0.003,
        "decay": 0.3,
        "sustain": 0.04,
        "release": 0.12
      },
      "gain": 0.14
    },
    "sparkle": {
      "layers": [
        {
          "source": {
            "type": "sine",
            "frequency": 1047,
            "detune": 7,
            "fm": {
              "ratio": 3.5,
              "depth": 200
            }
          },
          "envelope": {
            "attack": 0,
            "decay": 0.4,
            "sustain": 0.04,
            "release": 0.18
          },
          "effects": [
            {
              "type": "reverb",
              "decay": 0.8,
              "damping": 0.5,
              "mix": 0.15
            }
          ],
          "gain": 0.12
        },
        {
          "source": {
            "type": "sine",
            "frequency": 1050,
            "fm": {
              "ratio": 3.5,
              "depth": 180
            }
          },
          "envelope": {
            "attack": 0,
            "decay": 0.38,
            "sustain": 0.03,
            "release": 0.18
          },
          "gain": 0.08
        }
      ]
    },
    "star": {
      "source": {
        "type": "sine",
        "frequency": 880,
        "fm": {
          "ratio": 2.76,
          "depth": 250
        }
      },
      "envelope": {
        "attack": 0,
        "decay": 0.4,
        "sustain": 0.04,
        "release": 0.18
      },
      "effects": [
        {
          "type": "reverb",
          "decay": 0.6,
          "damping": 0.5,
          "mix": 0.12
        }
      ],
      "gain": 0.14
    },
    "error": {
      "layers": [
        {
          "source": {
            "type": "sawtooth",
            "frequency": {
              "start": 320,
              "end": 140
            }
          },
          "filter": {
            "type": "lowpass",
            "frequency": 1200
          },
          "envelope": {
            "attack": 0,
            "decay": 0.25,
            "sustain": 0,
            "release": 0.08
          },
          "gain": 0.22
        },
        {
          "source": {
            "type": "square",
            "frequency": {
              "start": 180,
              "end": 80
            }
          },
          "filter": {
            "type": "lowpass",
            "frequency": 800
          },
          "envelope": {
            "attack": 0,
            "decay": 0.2,
            "sustain": 0,
            "release": 0.06
          },
          "delay": 0.03,
          "gain": 0.12
        }
      ]
    },
    "delete": {
      "layers": [
        {
          "source": {
            "type": "sawtooth",
            "frequency": {
              "start": 300,
              "end": 100
            }
          },
          "filter": {
            "type": "lowpass",
            "frequency": 800
          },
          "envelope": {
            "attack": 0,
            "decay": 0.3,
            "sustain": 0,
            "release": 0.08
          },
          "gain": 0.18
        },
        {
          "source": {
            "type": "square",
            "frequency": {
              "start": 200,
              "end": 60
            }
          },
          "filter": {
            "type": "lowpass",
            "frequency": 600
          },
          "envelope": {
            "attack": 0,
            "decay": 0.25,
            "sustain": 0,
            "release": 0.06
          },
          "delay": 0.02,
          "gain": 0.1
        }
      ]
    },
    "warning": {
      "layers": [
        {
          "source": {
            "type": "triangle",
            "frequency": 440
          },
          "envelope": {
            "attack": 0,
            "decay": 0.18,
            "sustain": 0.06,
            "release": 0.06
          },
          "gain": 0.2
        },
        {
          "source": {
            "type": "triangle",
            "frequency": 466
          },
          "envelope": {
            "attack": 0,
            "decay": 0.18,
            "sustain": 0.06,
            "release": 0.06
          },
          "delay": 0.01,
          "gain": 0.15
        }
      ]
    },
    "swoosh": {
      "source": {
        "type": "noise",
        "color": "white"
      },
      "filter": {
        "type": "bandpass",
        "frequency": 300,
        "resonance": 1.8,
        "envelope": {
          "attack": 0.01,
          "peak": 4000,
          "decay": 0.08
        }
      },
      "envelope": {
        "attack": 0.01,
        "decay": 0.12,
        "sustain": 0,
        "release": 0.04
      },
      "gain": 0.12
    },
    "whoosh": {
      "source": {
        "type": "noise",
        "color": "white"
      },
      "filter": {
        "type": "bandpass",
        "frequency": 300,
        "resonance": 1.5,
        "envelope": {
          "attack": 0.04,
          "peak": 4000,
          "decay": 0.16
        }
      },
      "envelope": {
        "attack": 0.02,
        "decay": 0.25,
        "sustain": 0,
        "release": 0.08
      },
      "gain": 0.15
    },
    "page-enter": {
      "source": {
        "type": "noise",
        "color": "white"
      },
      "filter": {
        "type": "bandpass",
        "frequency": 400,
        "resonance": 1.2,
        "envelope": {
          "attack": 0.03,
          "peak": 3000,
          "decay": 0.15
        }
      },
      "envelope": {
        "attack": 0.02,
        "decay": 0.2,
        "sustain": 0,
        "release": 0.06
      },
      "gain": 0.08
    },
    "page-exit": {
      "source": {
        "type": "noise",
        "color": "pink"
      },
      "filter": {
        "type": "bandpass",
        "frequency": 2500,
        "resonance": 1.2,
        "envelope": {
          "decay": 0.18,
          "peak": 400
        }
      },
      "envelope": {
        "attack": 0.01,
        "decay": 0.2,
        "sustain": 0,
        "release": 0.06
      },
      "gain": 0.07
    },
    "tab-switch": {
      "source": {
        "type": "sine",
        "frequency": {
          "start": 1100,
          "end": 1500
        },
        "fm": {
          "ratio": 0.5,
          "depth": 50
        }
      },
      "envelope": {
        "attack": 0,
        "decay": 0.05,
        "sustain": 0,
        "release": 0.015
      },
      "gain": 0.18
    },
    "drawer-open": {
      "source": {
        "type": "sine",
        "frequency": {
          "start": 350,
          "end": 1000
        }
      },
      "envelope": {
        "attack": 0,
        "decay": 0.1,
        "sustain": 0,
        "release": 0.03
      },
      "gain": 0.08
    },
    "drawer-close": {
      "source": {
        "type": "sine",
        "frequency": {
          "start": 800,
          "end": 350
        }
      },
      "envelope": {
        "attack": 0,
        "decay": 0.1,
        "sustain": 0,
        "release": 0.03
      },
      "gain": 0.06
    },
    "modal-open": {
      "source": {
        "type": "sine",
        "frequency": {
          "start": 430,
          "end": 1400
        }
      },
      "envelope": {
        "attack": 0,
        "decay": 0.08,
        "sustain": 0,
        "release": 0.025
      },
      "gain": 0.1
    },
    "modal-close": {
      "source": {
        "type": "sine",
        "frequency": {
          "start": 730,
          "end": 430
        }
      },
      "envelope": {
        "attack": 0,
        "decay": 0.08,
        "sustain": 0,
        "release": 0.025
      },
      "gain": 0.08
    },
    "dropdown-open": {
      "source": {
        "type": "sine",
        "frequency": {
          "start": 500,
          "end": 1200
        }
      },
      "envelope": {
        "attack": 0,
        "decay": 0.06,
        "sustain": 0,
        "release": 0.02
      },
      "gain": 0.07
    },
    "dropdown-close": {
      "source": {
        "type": "sine",
        "frequency": {
          "start": 900,
          "end": 500
        }
      },
      "envelope": {
        "attack": 0,
        "decay": 0.06,
        "sustain": 0,
        "release": 0.02
      },
      "gain": 0.05
    },
    "slide": {
      "source": {
        "type": "noise",
        "color": "white"
      },
      "filter": {
        "type": "bandpass",
        "frequency": 500,
        "resonance": 1,
        "envelope": {
          "attack": 0.02,
          "peak": 3000,
          "decay": 0.12
        }
      },
      "envelope": {
        "attack": 0.01,
        "decay": 0.15,
        "sustain": 0,
        "release": 0.05
      },
      "gain": 0.07
    },
    "slide-up": {
      "source": {
        "type": "noise",
        "color": "white"
      },
      "filter": {
        "type": "bandpass",
        "frequency": 500,
        "resonance": 1,
        "envelope": {
          "attack": 0.02,
          "peak": 3500,
          "decay": 0.12
        }
      },
      "envelope": {
        "attack": 0.01,
        "decay": 0.15,
        "sustain": 0,
        "release": 0.05
      },
      "gain": 0.07
    },
    "slide-down": {
      "source": {
        "type": "noise",
        "color": "pink"
      },
      "filter": {
        "type": "bandpass",
        "frequency": 2500,
        "resonance": 1,
        "envelope": {
          "decay": 0.12,
          "peak": 500
        }
      },
      "envelope": {
        "attack": 0.01,
        "decay": 0.15,
        "sustain": 0,
        "release": 0.05
      },
      "gain": 0.06
    },
    "copy": {
      "layers": [
        {
          "source": {
            "type": "sine",
            "frequency": 1200
          },
          "envelope": {
            "attack": 0,
            "decay": 0.015,
            "sustain": 0,
            "release": 0.006
          },
          "gain": 0.16
        },
        {
          "source": {
            "type": "sine",
            "frequency": 1400
          },
          "envelope": {
            "attack": 0,
            "decay": 0.015,
            "sustain": 0,
            "release": 0.006
          },
          "delay": 0.04,
          "gain": 0.14
        }
      ]
    },
    "send": {
      "source": {
        "type": "sine",
        "frequency": {
          "start": 500,
          "end": 1200
        }
      },
      "envelope": {
        "attack": 0,
        "decay": 0.15,
        "sustain": 0,
        "release": 0.04
      },
      "gain": 0.16
    },
    "receive": {
      "source": {
        "type": "sine",
        "frequency": {
          "start": 1200,
          "end": 700
        }
      },
      "envelope": {
        "attack": 0,
        "decay": 0.12,
        "sustain": 0.02,
        "release": 0.04
      },
      "gain": 0.12
    },
    "command": {
      "layers": [
        {
          "source": {
            "type": "sine",
            "frequency": {
              "start": 600,
              "end": 900
            }
          },
          "envelope": {
            "attack": 0,
            "decay": 0.05,
            "sustain": 0,
            "release": 0.015
          },
          "gain": 0.18
        },
        {
          "source": {
            "type": "sine",
            "frequency": {
              "start": 900,
              "end": 1100
            }
          },
          "envelope": {
            "attack": 0,
            "decay": 0.04,
            "sustain": 0,
            "release": 0.012
          },
          "delay": 0.04,
          "gain": 0.12
        }
      ]
    },
    "escape": {
      "layers": [
        {
          "source": {
            "type": "sine",
            "frequency": {
              "start": 900,
              "end": 600
            }
          },
          "envelope": {
            "attack": 0,
            "decay": 0.05,
            "sustain": 0,
            "release": 0.015
          },
          "gain": 0.16
        },
        {
          "source": {
            "type": "sine",
            "frequency": {
              "start": 700,
              "end": 500
            }
          },
          "envelope": {
            "attack": 0,
            "decay": 0.04,
            "sustain": 0,
            "release": 0.012
          },
          "delay": 0.03,
          "gain": 0.1
        }
      ]
    },
    "undo": {
      "source": {
        "type": "sine",
        "frequency": {
          "start": 900,
          "end": 600
        }
      },
      "envelope": {
        "attack": 0,
        "decay": 0.12,
        "sustain": 0.02,
        "release": 0.04
      },
      "gain": 0.14
    },
    "archive": {
      "source": {
        "type": "sine",
        "frequency": {
          "start": 800,
          "end": 550
        }
      },
      "envelope": {
        "attack": 0.003,
        "decay": 0.15,
        "sustain": 0.02,
        "release": 0.05
      },
      "gain": 0.12
    },
    "sync": {
      "layers": [
        {
          "source": {
            "type": "sine",
            "frequency": 523
          },
          "envelope": {
            "attack": 0,
            "decay": 0.015,
            "sustain": 0,
            "release": 0.005
          },
          "gain": 0.14
        },
        {
          "source": {
            "type": "sine",
            "frequency": 784
          },
          "envelope": {
            "attack": 0,
            "decay": 0.015,
            "sustain": 0,
            "release": 0.005
          },
          "delay": 0.04,
          "gain": 0.12
        }
      ]
    },
    "heart": {
      "layers": [
        {
          "source": {
            "type": "sine",
            "frequency": {
              "start": 500,
              "end": 300
            }
          },
          "envelope": {
            "attack": 0,
            "decay": 0.1,
            "sustain": 0,
            "release": 0.04
          },
          "gain": 0.16
        },
        {
          "source": {
            "type": "sine",
            "frequency": 523,
            "fm": {
              "ratio": 2.5,
              "depth": 100
            }
          },
          "envelope": {
            "attack": 0.008,
            "decay": 0.25,
            "sustain": 0.04,
            "release": 0.1
          },
          "gain": 0.1
        }
      ]
    },
    "streak": {
      "layers": [
        {
          "source": {
            "type": "sine",
            "frequency": {
              "start": 523,
              "end": 784
            }
          },
          "envelope": {
            "attack": 0,
            "decay": 0.12,
            "sustain": 0.02,
            "release": 0.05
          },
          "gain": 0.16
        },
        {
          "source": {
            "type": "sine",
            "frequency": {
              "start": 526,
              "end": 787
            },
            "fm": {
              "ratio": 2.5,
              "depth": 100
            }
          },
          "envelope": {
            "attack": 0,
            "decay": 0.11,
            "sustain": 0.01,
            "release": 0.05
          },
          "gain": 0.08
        }
      ]
    },
    "loading-start": {
      "source": {
        "type": "sine",
        "frequency": {
          "start": 500,
          "end": 700
        }
      },
      "envelope": {
        "attack": 0.008,
        "decay": 0.12,
        "sustain": 0.02,
        "release": 0.05
      },
      "gain": 0.08
    },
    "loading-end": {
      "layers": [
        {
          "source": {
            "type": "sine",
            "frequency": {
              "start": 700,
              "end": 880
            }
          },
          "envelope": {
            "attack": 0,
            "decay": 0.1,
            "sustain": 0.02,
            "release": 0.04
          },
          "gain": 0.1
        },
        {
          "source": {
            "type": "sine",
            "frequency": {
              "start": 880,
              "end": 1046
            }
          },
          "envelope": {
            "attack": 0,
            "decay": 0.08,
            "sustain": 0.01,
            "release": 0.04
          },
          "delay": 0.06,
          "gain": 0.08
        }
      ]
    },
    "progress-tick": {
      "source": {
        "type": "sine",
        "frequency": 1400,
        "fm": {
          "ratio": 0.5,
          "depth": 50
        }
      },
      "envelope": {
        "attack": 0,
        "decay": 0.01,
        "sustain": 0,
        "release": 0.004
      },
      "gain": 0.1
    }
  }
};
